import typescript from '@rollup/plugin-typescript';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';

const isProd = (process.env.BUILD === 'production');

const banner = 
`/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source, please visit the github repository of this plugin
*/
`;

export default {
  input: 'main.ts',
  output: {
    dir: '.',
    sourcemap: 'inline',
    sourcemapExcludeSources: isProd,
    format: 'cjs',
    exports: 'default',
    banner,
  },
  external: ['obsidian', 'electron', 'fs', 'path', 'http', 'https', 'crypto', 'buffer', 'stream', 'util', 'events', 'querystring', 'url', 'net', 'tls', 'zlib', 'express', 'cors', 'body-parser'],
  plugins: [
    typescript(),
    nodeResolve({browser: true}),
    commonjs(),
    json()
  ]
};